name: LinkedIn DevOps Job Alert

on:
  schedule:
    - cron: '0,20,40 5-19 * * *'  # Every 20 mins, 08:00-21:59 Athens time (UTC+3)
  workflow_dispatch:

jobs:
  scrape-and-notify:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.44.0-focal
    env:
      TELEGRAM_BOT_API: ${{ secrets.TELEGRAM_BOT_API }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      LINKEDIN_EMAIL: ${{ secrets.LINKEDIN_EMAIL }}
      LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
      LINKEDIN_SESSION_FILE: linkedin_session.json
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Cache LinkedIn session
        uses: actions/cache@v4
        with:
          path: linkedin_session.json
          key: linkedin-session-${{ runner.os }}

      - name: List files before download
        run: |
          echo "Listing files before download:"
          ls -lR

      - name: Cache jobs cache
        uses: actions/cache@v4
        with:
          path: jobs_cache
          key: jobs-cache-${{ runner.os }}

      - name: List files after download
        run: |
          echo "Listing files after download:"
          ls -lR
      - name: Install Playwright and requests
        run: |
          pip install playwright requests pytz
          playwright install chromium
      - name: Run job alert script
        run: python temp.py

      - name: Print jobs cache file before upload
        run: |
          echo "[DEBUG] Listing jobs_cache directory before upload:"
          ls -l jobs_cache || true
          echo "[DEBUG] Printing jobs_cache/last_jobs.json contents:"
          cat jobs_cache/last_jobs.json || echo "[DEBUG] jobs_cache/last_jobs.json not found"
      - name: Upload jobs cache artifact (manual/debug only)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jobs-cache
          path: jobs_cache/last_jobs.json
      - name: Upload LinkedIn login debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: linkedin-login-debug
          path: |
            linkedin_login_failure.png
            linkedin_login_failure.html
      - name: Upload Playwright videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-videos
          path: playwright-videos/
